### ISSUE TITLE
ファイル名に「表」が含まれるエイリアスが正常に並び替えられない

### ISSUE THREAD

**Issue by krmz-krmz** [nazonoSAUNA/SortEffect#1]
設定ファイルに書いた位置・個数とは無関係に、`その他`に一つ配置されます。
また、Aviutlを起動するたび、設定ファイルの`その他`に追加されます。
![image](https://user-images.githubusercontent.com/71175240/188258692-dd046516-146f-4e66-8081-329c0007e87c.png)

**Comment by nazonoSAUNA** [comment]
2バイト文字の判定をしていないのが原因みたいですね。
表の文字コード → 149 92
\の文字コード → 92

**Comment by nazonoSAUNA** [comment]
v1.1にて修正しました
